server:
  port: 8081

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      x-forwarded:
         enabled: false
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes: 
        - id: api-service
          uri: lb://API-SERVICE
          predicates:
            - Path=/api/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://registry-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
