

server:
  port: 8080

spring:
  cassandra:
    contact-points:
      - localhost:9042
      - localhost:9043
      - localhost:9044
    port: 9042
    keyspace-name: restaurant
    local-datacenter: dc1

eureka:
  client:
    service-url:
      defaultZone: http://registry-server:8761/eureka
  instance:
    prefer-ip-address: true

