server:
  port: 0

spring:
  cassandra:
    contact-points:
      - cassandra-1
      - cassandra-2
      - cassandra-3
    port: 9042
    keyspace-name: restaurant
    local-datacenter: dc1

eureka:
  client:
    service-url:
      defaultZone: http://registry-server:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
